### ISSUE TITLE
Release with Github

### ISSUE THREAD

**Issue by davelab6** [ssagano/Aileron#2]
Your homepage offers a ZIP at http://dotcolon.net/DL/font/aileron.zip and it would be great to tag the git commit that relates to that release, and attach that ZIP to that release at https://github.com/ssagano/Aileron/releases - with both the CC-0 and OFL license files included in that attached ZIP :)

**Comment by ssagano** [comment]
I just uploaded font files. This is not there a problem?

**Comment by davelab6** [comment]
Its not quite what I meant. If the glyphs files in this repo match the OTF files in the ZIP you uploaded, then remove the ZIP from the repo, then in Terminal run

```sh
cd path/to/this/git/folder/;
git tag v0.102;
git push --tags;
```

then you will see that commit appear in https://github.com/ssagano/Aileron/releases and then you can click the 'edit' button and drag and drop the ZIP into that issue.

**Comment by ssagano** [comment]
Thank you. I'm not used to how to use the git. sorry.

**Comment by davelab6** [comment]
Don't worry!! :) We are all learning how fonts can work on Git together :)
